// type: para indicar la acción que se va a ejecutar.

// AUTH
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';

// SHOPS
export const SET_FAVORITE_SHOP = 'SET_FAVORITE_SHOP';
export const REMOVE_FAVORITE_SHOP = 'REMOVE_FAVORITE_SHOP';

// SEARCH
export const SEARCH_REQUEST = 'SEARCH_REQUEST';

// SHOPPING
export const SET_SUBCATERGORY_ID = 'SET_SUBCATERGORY_ID';
export const SET_SUBCATERGORY_NAME = 'SET_SUBCATERGORY_NAME';
export const SHOW_PRODUCTS_BY_SHOP = 'SHOW_PRODUCTS_BY_SHOP';
export const SHOW_PRODUCTS_BY_CATEGORY = 'SHOW_PRODUCTS_BY_CATEGORY';
export const SHOW_PRODUCTS_BY_SUBCATEGORY = 'SHOW_PRODUCTS_BY_SUBCATEGORY';
export const FILTER_BRANDS = 'FILTER_BRANDS';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const ADD_TO_CAR = 'ADD_TO_CAR';
export const REMOVE_OF_CAR = 'REMOVE_OF_CAR';

// PAGINATION
export const NUMBER = 'NUMBER';
export const SIZE = 'SIZE';
export const LAST = 'LAST';
export const FIRST = 'FIRST';
export const EMPTY = 'EMPTY';
export const NUMBER_OF_ELEMENTS = 'NUMBER_OF_ELEMENTS';
export const TOTAL_PAGES = 'TOTAL_PAGES';
export const TOTAL_ELEMENTS = 'TOTAL_ELEMENTS';

// USER
export const SET_SHOPPING_CARS = 'SET_SHOPPING_CARS';
export const SET_HISTORY_ORDER = 'SET_HISTORY_ORDER';
export const SAVE_CARD = 'SAVE_CARD';

// DO ORDER
export const SET_ORDER = 'SET_ORDER';
export const SET_ORDER_COORDENATES = 'SET_ORDER_COORDENATES';
export const SET_ORDER_SHOP_ID = 'SET_ORDER_SHOP_ID';
export const SET_ORDER_SHOPPING_CAR = 'SET_ORDER_SHOPPING_CAR';
export const SET_ORDER_SOURCE_ID = 'SET_ORDER_SOURCE_ID';

// FIREBASE NOTIFICATIONS
export const SET_REGISTRATION_DEVICE_ID = 'SET_REGISTRATION_DEVICE_ID';
export const SET_NOTIFICATION_KEY_AND_KEY_NAME =
  'SET_NOTIFICATION_KEY_AND_KEY_NAME';

// SHOW
export const SHOW_USER_ORDERS = 'SHOW_USER_ORDERS';
export const SHOW_USER_SHOPPING_CARS = 'SHOW_USER_SHOPPING_CARS';
export const SHOW_USER_CARDS = 'SHOW_USER_CARDS';
export const SHOW_USER_ACCOUNT = 'SHOW_USER_ACCOUNT';

// ERROR
export const SET_ERROR = 'SET_ERROR';

// LOADING
export const ENABLE_LOADING = 'ENABLE_LOADING';
export const DISABLE_LOADING = 'DISABLE_LOADING';

// MAPS
export const LOAD_GOOGLE_MAP = 'LOAD_GOOGLE_MAP';
