// type: para indicar la acción que se va a ejecutar.

// AUTH
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';

// SHOPS
export const SET_FAVORITE_SHOP = 'SET_FAVORITE_SHOP';
export const REMOVE_FAVORITE_SHOP = 'REMOVE_FAVORITE_SHOP';

// SEARCH
export const SEARCH_REQUEST = 'SEARCH_REQUEST';

// SHOPPING
export const SHOW_PRODUCTS_BY_SHOP = 'SHOW_PRODUCTS_BY_SHOP';
export const SHOW_PRODUCTS_BY_CATEGORY = 'SHOW_PRODUCTS_BY_CATEGORY';
export const SHOW_PRODUCTS_BY_SUBCATEGORY = 'SHOW_PRODUCTS_BY_SUBCATEGORY';

export const FILTER_BRANDS = 'FILTER_BRANDS';

export const SORT_PRODUCTS = 'SORT_PRODUCTS';

// export const ORDER_BY_HIGHER_COST = 'ORDER_BY_HIGHER_COST';
// export const ORDER_BY_LOWER_COST = 'ORDER_BY_LOWER_COST';
// export const ORDER_BY_PRODUCT_NAME = 'ORDER_BY_PRODUCT_NAME';
// export const ORDER_BY_STOCK = 'ORDER_BY_STOCK';

export const ADD_TO_CAR = 'ADD_TO_CAR';
export const REMOVE_OF_CAR = 'REMOVE_OF_CAR';

// PAY
export const SET_ORDER = 'SET_ORDER';
export const SAVE_CARD = 'SAVE_CARD';

// SHOW
export const SHOW_USER_ORDERS = 'SHOW_USER_ORDERS';
export const SHOW_USER_SHOPPING_CARS = 'SHOW_USER_SHOPPING_CARS';
export const SHOW_USER_CARDS = 'SHOW_USER_CARDS';
export const SHOW_USER_ACCOUNT = 'SHOW_USER_ACCOUNT';

// ERROR
export const SET_ERROR = 'SET_ERROR';
